"""Sales Table V2

Revision ID: 12749494f563
Revises: d0a285b3e4b2
Create Date: 2026-03-26 22:54:46.737070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12749494f563'
down_revision: Union[str, Sequence[str], None] = 'd0a285b3e4b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_name', sa.String(), nullable=False),
    sa.Column('buyer_email', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('method_of_payment', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('sale_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('unique_code', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_code')
    )
    op.create_index(op.f('ix_sales_buyer_email'), 'sales', ['buyer_email'], unique=False)
    op.create_index(op.f('ix_sales_buyer_name'), 'sales', ['buyer_name'], unique=False)
    op.create_index(op.f('ix_sales_id'), 'sales', ['id'], unique=False)
    op.create_index(op.f('ix_sales_status'), 'sales', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_status'), table_name='sales')
    op.drop_index(op.f('ix_sales_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_buyer_name'), table_name='sales')
    op.drop_index(op.f('ix_sales_buyer_email'), table_name='sales')
    op.drop_table('sales')
    # ### end Alembic commands ###
