"""Edicoes Model Event and Product

Revision ID: 81462762794f
Revises: 12749494f563
Create Date: 2026-03-27 22:22:10.141271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81462762794f'
down_revision: Union[str, Sequence[str], None] = '12749494f563'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('location', sa.String(), nullable=True))
    op.add_column('product', sa.Column('available_quantity', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('is_active', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('sales', sa.Column('checkin_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'checkin_at')
    op.drop_column('product', 'is_active')
    op.drop_column('product', 'available_quantity')
    op.drop_column('event', 'location')
    # ### end Alembic commands ###
