"""Correção de Products

Revision ID: efecfc98d10e
Revises: 81462762794f
Create Date: 2026-03-27 22:33:13.453136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efecfc98d10e'
down_revision: Union[str, Sequence[str], None] = '81462762794f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # 1. Remove o server_default antigo
    op.alter_column('product', 'is_active', server_default=None)
    
    # 2. Converte para boolean
    op.alter_column('product', 'is_active',
        existing_type=sa.Integer(),
        type_=sa.Boolean(),
        postgresql_using='is_active::boolean',
        server_default='true'
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'is_active',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    # ### end Alembic commands ###
